label: "momo-storybook"
pdf_path: "assets/momo.pdf"

input_language: en
plate_language: en
output_languages: [en, fr]

output_dir: "output"
run_output_dir: "${output_dir}/${label}"

clear_cache: false
print_available_models: false

# our strategy for cropping, either llm or none
crop_strategy: none

# our glossary strategy, either llm or none
glossary_strategy: none

# our explanation strategy, either llm or none
explanation_strategy: none

# our easy read strategy, either llm or none
easy_read_strategy: none

# our caption strategy, either llm or none
caption_strategy: none

# our TTS / speech strategy, either tts or none
speech_strategy: none

# if specified, the plate at this path will be used to generate the ADT
custom_plate_path: ""

# the default model used for all prompts, unless overridden in a specific prompt config
default_model: gpt-4o

# what strategy is used to render sections into web pages, dynamic will choose based on layout type
render_strategy: two_column

layout_types:
  single_column:
    description: "Single column layout with text and images flowing in one main column across the page."    
    render_strategy: two_column

  two_column: 
    description: "Two column layout with text and images arranged in two distinct columns side by side."
    render_strategy: two_column

  overlay:
    description: "Overlay layout with text overlaid on images, often with speech bubbles or captions."
    render_strategy: overlay

  other:
    description: "Other layout type that does not fit any of the other categories. "
    render_strategy: two_column

render_strategies:
  single_column:
    render_type: template
    config:
      render_template_path: templates/single_column_render.html

  two_column:
    render_type: template
    config:
      render_template_path: templates/two_column_template_render.html

  overlay:
    render_type: html
    config:
      model: default
      template_path: prompts/web_generation_html_fit_overlay.jinja2
      max_retries: 25

  html:
    render_type: html
    config:
      model: default
      template_path: prompts/web_generation_html.jinja2
      max_retries: 25

      example_dirs:
        - assets/prompts/adt_examples/text_only_1
        - assets/prompts/adt_examples/text_and_images_1
        - assets/prompts/adt_examples/text_and_images_2
        - assets/prompts/adt_examples/text_and_images_3

  rows:
    render_type: rows
    config:
      model: default    
      template_path: prompts/web_generation_rows.jinja2
      render_template_path: templates/row_render.html

page_range:
  start: 0
  end: 5

image_filters:
  size:
    max_side: 3500
    min_side: 150

  blank:
    threshold: 2

text_filters:
  pruned_text_types:
    - footer_text
    - page_number
    - other

section_filters:
  pruned_section_types:
    - back_cover
    - credits
    - inside_cover
   

prompts:
  text_extraction:
    model: default
    template_path: prompts/text_extraction_groups.jinja2

  meaningfulness:
    model: default
    template_path: prompts/image_meaningfulness.jinja2

  crop:
    model: default
    template_path: prompts/image_crop_storybook.jinja2
    recrop_template_path: prompts/image_recrop_storybook.jinja2
    recrops: 2

  caption:
    model: default
    template_path: prompts/image_caption.jinja2

  page_sectioning:
    model: default
    template_path: prompts/page_sectioning_by_page.jinja2
    max_retries: 10

  section_explanation:
    model: default
    template_path: prompts/section_explanation.jinja2
   
  text_translation:
    model: default
    template_path: prompts/text_translation.jinja2

  glossary_translation:
    model: default
    template_path: prompts/glossary_translation.jinja2

  section_glossary:
    model: default
    template_path: prompts/section_glossary.jinja2

  section_metadata:
    model: default
    template_path: prompts/section_metadata.jinja2

  text_easy_read:
    model: default
    template_path: prompts/text_easy_read.jinja2

  speech_generation:
    model: gpt-4o-mini-tts
    template_path: prompts/speech_generation.jinja2
