# An example config for storybooks like Molly Hopper - this book is a single page portrait storybook with text and images

label: "molly-twoColumns"
pdf_path: "assets/molly.pdf"

input_language: en
plate_language: en
output_languages: [en, es]

output_dir: "output"
run_output_dir: "${output_dir}/${label}"

clear_cache: false
print_available_models: false

# whether to have the LLM generate full HTML web pages or structured rows
web_strategy: twoColumns

# our strategy for cropping, either llm or none
crop_strategy: llm

# if specified, the plate at this path will be used to generate the ADT
custom_plate_path: ""

# the default model used for all prompts, unless overridden in a specific prompt config
default_model: gpt-5

page_range:
  start: 0
  end: 0

image_filters:
  size:
    max_side: 2500
    min_side: 150

  blank:
    threshold: 2

text_filters:
  pruned_text_types:
    - footer_text
    - page_number
    - other

section_filters:
  pruned_section_types:
    - back_cover
    - credits

prompts:
  text_extraction:
    model: default
    template_path: prompts/text_extraction.jinja2

  meaningfulness:
    model: default
    template_path: prompts/image_meaningfulness.jinja2

  crop:
    model: default
    template_path: prompts/image_crop.jinja2
    recrop_template_path: prompts/image_recrop.jinja2
    recrops: 1

  caption:
    model: default
    template_path: prompts/image_caption.jinja2

  page_sectioning:
    model: default
    template_path: prompts/page_sectioning.jinja2
    max_retries: 10

  section_explanation:
    model: default
    template_path: prompts/section_explanation.jinja2
   
  text_translation:
    model: default
    template_path: prompts/text_translation.jinja2

  section_glossary:
    model: default
    template_path: prompts/section_glossary.jinja2

  section_easy_read:
    model: default
    template_path: prompts/section_easy_read.jinja2

  web_generation_html:
    model: default
    template_path: prompts/web_generation_html.jinja2
    max_retries: 25

    example_dirs:
      - assets/prompts/adt_examples/text_only_1
      - assets/prompts/adt_examples/text_and_images_1
      - assets/prompts/adt_examples/text_and_images_2
      - assets/prompts/adt_examples/text_and_images_3

  web_generation_rows:
    model: default    
    template_path: prompts/web_generation_rows.jinja2
    row_template_path: templates/row_render.html

  web_generation_twoColumns:
    model: default
    template_path: prompts/web_generation_twoColumns.jinja2
    row_template_path: templates/twoColumns_render.html

  speech_generation:
    model: gpt-4o-mini-tts
    template_path: prompts/speech_generation.jinja2
