# eval tasks go to `output/eval` by default
label: eval

task: "text_translation"
# experiment: "???"
# prompt: "???"
# dataset: "???"

# input language defaults to English
input_language: en


# ADT Evaluation Configuration
eval:

  # limit to only this many tests per task
  limit: 9999

  # our rate limit (per minute) on calls to the LLM
  rate_limit: 300

  # Tasks to run (empty list means run all available tasks)
  tasks: []

  # Task-specific configurations
  task_configs:
    text_type:
      label_studio_project_name: "A2: Text Type"
      model: ${default_model}
      prompt: ${prompts.text_extraction}
      report_template_path: templates/eval/text_type_report.html
    text_translation:
      model: ${default_model}
      prompt: ${prompts.text_translation}
      report_template_path: templates/eval/translation_report.html
      experiments:
        - experiment_name: "adt_press_translation_task_experiment_20"
          task: "text_translation"
          report_template_path: templates/eval/text_translation_report.html
          tags:
            - key: "task"
              value: "text_translation"
          model: "gpt-5-mini" # This is the model used for the experiment run
          input_language: "en"
          output_language: "es"
          prompt:
            name: "text_translation.jinja2"
            version: "1"
            template_path: "prompts:/text_translation.jinja2/1"
            tags:
              - key: "task"
                value: "translation"
            optimization:
              is_enabled: false
              metric_name: "is_acceptable_translation"
              metric_threshold: 0.95
              max_iterations: 3
          dataset:
            label_studio_project_name: "A2: Text Type"
            name: "text_type_eval_dataset_20"