# eval tasks go to `output/eval` by default
label: eval

# input language defaults to English
input_language: en

# Tasks to run (empty list means run all available tasks)
tasks_to_run: []

# ADT Evaluation Configuration
eval:

  # limit to only this many tests per task
  limit: 9999

  # our rate limit (per minute) on calls to the LLM
  rate_limit: 300

  # MLflow evaluation settings
  mlflow:
    disable_tracing: true

  # Task-specific configurations
  task_configs:
    text_type:
      label_studio_project_name: "A2: Text Type"
      model: ${default_model}
      prompt: ${prompts.text_extraction}
      report_template_path: templates/eval/text_type_report.html
    text_transcription:
      label_studio_project_name: "A1: Text Extraction"
      model: ${default_model}
      prompt: ${prompts.text_extraction}
      report_template_path: templates/eval/text_transcription_report.html

  # Whether to use cached log files instead of calling the LLM (useful for debugging)
  use_cached_llm_results: False
