name: Deploy Sample

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write
  checks: write
  pull-requests: write

concurrency:
  group: "sample"
  cancel-in-progress: true

jobs:
  build-sample:
    environment: sample
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2

      - name: Install dependencies
        run: sudo apt install libcairo2-dev pkg-config python3-dev

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Update lockfile
        run: uv lock

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run ADT Press
        run: |
          uv run adt-press.py pdf_path=./assets/momo.pdf label=momo
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload sample artifact
        uses: actions/upload-artifact@v4
        with:
          name: sample-${{ github.run_id }}
          path: output/momo/

  push-azure:
    needs: build-sample
    environment: sample
    runs-on: ubuntu-latest
    steps:          
      - name: Download sample artifact
        uses: actions/download-artifact@v4
        with:
          name: sample-${{ github.run_id }}
          path: output/momo/

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
              az storage blob upload-batch -d '$web' -s output/momo/ --overwrite --destination-path sample/
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
