name: Build and Test Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t adt-press .

      - name: Check Python dependencies in Docker
        env:
          OPENAI_API_KEY: dummy-key
        run: |
          docker run --rm -e OPENAI_API_KEY=$OPENAI_API_KEY adt-press uv run python -c "import asynciolimiter, banks, fsspec, google.genai, graphviz, hydra, instructor, jinja2, jsonref, langfuse, litellm, matplotlib, numpy, openai, cv2, PIL, pydantic, fitz, yaml, rich, ruff, hamilton, structlog, upath; print('All dependencies imported successfully')"

      - name: Run tests in Docker
        env:
          OPENAI_API_KEY: dummy-key
        run: |
          docker run --rm -e OPENAI_API_KEY=$OPENAI_API_KEY adt-press uv run pytest