name: Format and Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Format code 
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check --diff"
