name: Generate Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  checks: write
  pull-requests: write

concurrency:
  group: preview
  cancel-in-progress: true

jobs:
  build-preview:
    environment: preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2

      - name: Install dependencies
        run: sudo apt install libcairo2-dev pkg-config python3-dev

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Update lockfile
        run: uv lock

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run ADT Press
        run: |
          uv run adt-press.py pdf_path=./assets/momo.pdf label=momo page_range.end=5
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  push-azure:
    needs: build-preview
    environment: preview
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:          
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
              az storage blob upload-batch -d '$web' -s output/momo/ --overwrite true --destination-path actions/prs/${{ github.event.number }}/preview/
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}

      - name: Comment PR with preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Create comment body
            const adtURL = `https://adtpress.z1.web.core.windows.net/actions/prs/${{ github.event.number }}/preview/index.html`;
            
            let commentBody = `## ADT Preview\n\n`;
            commentBody += `[View preview ADT](${adtURL})\n\n`;
            commentBody += `*ADT generated for commit: ${{ github.event.pull_request.head.sha }}*`;
            
            // Post comment
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });

  cleanup-azure:
    environment: preview
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - name: Delete eval preview from blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
              az storage blob delete-batch -s '$web' --pattern "actions/prs/${{ github.event.number }}/preview/*"
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}