name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  pull-requests: write
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v2

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install dependencies
      run: sudo apt install libcairo2-dev pkg-config python3-dev build-essential

    - name: Update lockfile
      run: uv lock

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Run tests
      run: uv run coverage run -m pytest
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Generate coverage report
      run: uv run coverage report -m

    - name: Add coverage comment
      uses: py-cov-action/python-coverage-comment-action@v3
      with:
        GITHUB_TOKEN: ${{ github.token }}
